name: Build ALIET Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ALIET_CGPA_Calculator_APK_READY

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check project files
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la

      - name: Install dependencies
        run: npm install

      - name: Add Android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Make Gradle executable
        working-directory: ./ALIET_CGPA_Calculator_APK_READY/android
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: ./ALIET_CGPA_Calculator_APK_READY/android
        run: ./gradlew assembleDebug

      - name: Check APK
        run: |
          echo "APK files:"
          find android/app/build/outputs/apk -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ALIET-CGPA-Calculator-APK
          path: ALIET_CGPA_Calculator_APK_READY/android/app/build/outputs/apk/debug/app-debug.apk
